apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-flask-config
data:
  APP_MESSAGE: "Hello from a Kubernetes ConfigMap!"
  DB_HOST: postgres-service
  DB_NAME: shopping
  DB_USER: shopping
  ADMIN_USERNAME: admin
  ADMIN_PASSWORD: changeme-admin-password
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-flask-config-mount
data:
  app_config.json: |
    {
      "message": "Hello from a mounted ConfigMap file!"
    }
